version: "2"

checks:
    argument-count:
        enabled: true
        config:
            threshold: 10
    complex-logic:
        enabled: true
        config:
            threshold: 6
    file-lines:
        enabled: true
        config:
            threshold: 250
    method-complexity:
        enabled: true
        config:
            threshold: 5
    method-count:
        enabled: true
        config:
            threshold: 20
    method-lines:
        enabled: true
        config:
            threshold: 25
    nested-control-flow:
        enabled: true
        config:
            threshold: 4
    return-statements:
        enabled: true
        config:
            threshold: 4
    similar-code:
        enabled: true
        config:
            threshold: #language-specific defaults. overrides affect all languages.
    identical-code:
        enabled: true
        config:
            threshold: #language-specific defaults. overrides affect all languages.

plugins:
    bandit:
        enabled: true
    pep8:
        enabled: true
    radon:
        enabled: true
    fixme:
        enabled: true
    sonar-python:
        enabled: true
        config:
            tests_patterns:
                - tests/**

exclude_patterns:
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "**/vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"
